<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $products = [
            [
                'team_id' => 1,
                'category_id' => 2,
                'brand_id' => 2,
                'name' => 'Aloe Soothing Sun Cream',
                'slug' => 'aloe-soothing-sun-cream',
                'sku' => '000001',
                'description' => null,
                'image' => null,
                'cost_price' => 9.58,
                'sale_price' => 20.00,
                'stock' => 0,
                'min_stock' => 5,
                'active' => true,
            ],
            [
                'team_id' => 1,
                'category_id' => 3,
                'brand_id' => 2,
                'name' => 'Acne Pimple Master Patch',
                'slug' => 'acne-pimple-master-patch',
                'sku' => '000002',
                'description' => null,
                'image' => null,
                'cost_price' => 3.21,
                'sale_price' => 5.00,
                'stock' => 0,
                'min_stock' => 0,
                'active' => true,
            ],
            [
                'team_id' => 1,
                'category_id' => 3,
                'brand_id' => 2,
                'name' => 'Clear Fit Master Patch',
                'slug' => 'clear-fit-master-patch',
                'sku' => '000003',
                'description' => null,
                'image' => null,
                'cost_price' => 3.21,
                'sale_price' => 5.00,
                'stock' => 0,
                'min_stock' => 0,
                'active' => true,
            ],
            [
                'team_id' => 1,
                'category_id' => 1,
                'brand_id' => 3,
                'name' => 'PDRN Pink Peptide Serum Bundle',
                'slug' => 'pdrn-pink-peptide-serum-bundle',
                'sku' => '000004',
                'description' => null,
                'image' => null,
                'cost_price' => 14.35,
                'sale_price' => 25.00,
                'stock' => 0,
                'min_stock' => 0,
                'active' => true,
            ],
            [
                'team_id' => 1,
                'category_id' => 4,
                'brand_id' => 3,
                'name' => 'Collagen Night Wrapping Mask Bundle',
                'slug' => 'collagen-night-wrapping-mask-bundle',
                'sku' => '000005',
                'description' => null,
                'image' => null,
                'cost_price' => 14.89,
                'sale_price' => 25.00,
                'stock' => 0,
                'min_stock' => 0,
                'active' => true,
            ],
            [
                'team_id' => 1,
                'category_id' => 1,
                'brand_id' => 3,
                'name' => 'PDRN Pink Collagen Exosome Shot 7500',
                'slug' => 'pdrn-pink-collagen-exosome-shot-7500',
                'sku' => '000006',
                'description' => null,
                'image' => null,
                'cost_price' => 12.10,
                'sale_price' => 25.00,
                'stock' => 0,
                'min_stock' => 0,
                'active' => true,
            ],
            [
                'team_id' => 1,
                'category_id' => 5,
                'brand_id' => 3,
                'name' => 'Tónico Exfoliante',
                'slug' => 'tonico-exfoliante',
                'sku' => '000007',
                'description' => null,
                'image' => null,
                'cost_price' => 18.75,
                'sale_price' => 25.00,
                'stock' => 0,
                'min_stock' => 0,
                'active' => true,
            ],
            [
                'team_id' => 1,
                'category_id' => 1,
                'brand_id' => 4,
                'name' => 'Madagascar Centella Ampoule Kit Bundle',
                'slug' => 'madagascar-centella-ampoule-kit-bundle',
                'sku' => '000008',
                'description' => null,
                'image' => null,
                'cost_price' => 22.52,
                'sale_price' => 40.00,
                'stock' => 0,
                'min_stock' => 0,
                'active' => true,
            ],
            [
                'team_id' => 1,
                'category_id' => 1,
                'brand_id' => 4,
                'name' => 'Tone Brightening Ampoule Jumbo Bundle',
                'slug' => 'tone-brightening-ampoule-jumbo-bundle',
                'sku' => null,
                'description' => null,
                'image' => null,
                'cost_price' => 14.85,
                'sale_price' => 25.00,
                'stock' => 0,
                'min_stock' => 0,
                'active' => true,
            ],
            [
                'team_id' => 1,
                'category_id' => 1,
                'brand_id' => 4,
                'name' => 'Poremizing Fresh Ampoule Jumbo Bundle',
                'slug' => 'poremizing-fresh-ampoule-jumbo-bundle',
                'sku' => null,
                'description' => null,
                'image' => null,
                'cost_price' => 13.75,
                'sale_price' => 25.00,
                'stock' => 0,
                'min_stock' => 0,
                'active' => true,
            ],
            [
                'team_id' => 1,
                'category_id' => 2,
                'brand_id' => 4,
                'name' => 'Hyalu-Cica Water-Fit Sun Serum',
                'slug' => 'hyalu-cica-water-fit-sun-serum',
                'sku' => null,
                'description' => null,
                'image' => null,
                'cost_price' => 10.45,
                'sale_price' => 20.00,
                'stock' => 0,
                'min_stock' => 0,
                'active' => true,
            ],
            [
                'team_id' => 1,
                'category_id' => 1,
                'brand_id' => 1,
                'name' => 'Bean Essence Jumbo Bundle',
                'slug' => 'bean-essence-jumbo-bundle',
                'sku' => null,
                'description' => null,
                'image' => null,
                'cost_price' => 14.78,
                'sale_price' => 25.00,
                'stock' => 2,
                'min_stock' => 0,
                'active' => true,
            ],
            [
                'team_id' => 1,
                'category_id' => 6,
                'brand_id' => 1,
                'name' => 'Bean Cleansing Oil Jumbo Bundle',
                'slug' => 'bean-cleansing-oil-jumbo-bundle',
                'sku' => null,
                'description' => null,
                'image' => null,
                'cost_price' => 15.67,
                'sale_price' => 25.00,
                'stock' => 2,
                'min_stock' => 0,
                'active' => true,
            ],
            [
                'team_id' => 1,
                'category_id' => 7,
                'brand_id' => 1,
                'name' => 'Centella Cleansing Foam Bundle',
                'slug' => 'centella-cleansing-foam-bundle',
                'sku' => null,
                'description' => null,
                'image' => null,
                'cost_price' => 12.10,
                'sale_price' => 20.00,
                'stock' => 1,
                'min_stock' => 0,
                'active' => true,
            ],
            [
                'team_id' => 1,
                'category_id' => 2,
                'brand_id' => 1,
                'name' => 'Centella Sun Cream Bundle',
                'slug' => 'centella-sun-cream-bundle',
                'sku' => null,
                'description' => null,
                'image' => null,
                'cost_price' => 9.95,
                'sale_price' => 20.00,
                'stock' => 0,
                'min_stock' => 0,
                'active' => true,
            ],
            [
                'team_id' => 1,
                'category_id' => 8,
                'brand_id' => 1,
                'name' => 'Vitamin C 20 Serum',
                'slug' => 'vitamin-c-20-serum',
                'sku' => null,
                'description' => null,
                'image' => null,
                'cost_price' => 11.00,
                'sale_price' => 20.00,
                'stock' => 1,
                'min_stock' => 0,
                'active' => true,
            ],
        ];

        foreach ($products as $product) {
            Product::create($product);
        }
    }
}
